"""
Extremely lacking mock of the RPi.GPIO Module
Source code can be found here:
https://sourceforge.net/p/raspberry-gpio-python/code/ci/default/tree/
"""

# soruce/constants.c
HIGH = ...
LOW = ...
OUT = ...
IN = ...
HARD_PWM = ...
SERIAL = ...
I2C = ...
SPI = ...
UNKNOWN = ...
BOARD = ...
BCM = ...
PUD_OFF = ...
PUD_UP = ...
PUD_DOWN = ...
RISING = ...
FALLING = ...
BOTH = ...

# source/py_pwm.c
def start(*a, **kw): ...
def ChangeDutyCycle(*a, **kw): ...
def ChangeFrequency(*a, **kw): ...
def stop(*a, **kw): ...

# source/py_gpio.c
RPI_INFO = ...
RPI_REVISION = ...   # deprecated
PWM = ...

def setup(*a, **kw): ...
def cleanup(*a, **kw): ...
def output(*a, **kw): ...
def input(*a, **kw): ...
def setmode(*a, **kw): ...
def getmode(*a, **kw): ...
def add_event_detect(*a, **kw): ...
def remove_event_detect(*a, **kw): ...
def event_detected(*a, **kw): ...
def add_event_callback(*a, **kw): ...
def wait_for_edge(*a, **kw): ...
def gpio_function(*a, **kw): ...
def setwarnings(*a, **kw): ...


